file_fotmat: "1"
id: badwings
name: Badwings
type: shield
url: https://github.com/CallumABeale/BadWings
requires: [Nice!Nano]
exposes: [Nice!View]
features:
  - keys
  - display
  - encoder
  - underglow
  - studio
siblings:
  - badwings_left
  - badwings_right
